% set_GUI:
global h out_index Sample_frequency out save_data load_previous_data CPR
CPR = 14400;
%global h Freq__BOX Amp__BOX Sample_Duration_period_BOX Sine_PLOT Furier_PLOT out_index Sample_frequency out save_data Save_Data_checkbox
set(0,'DefaultFigureWindowStyle','normal')
save_data = 1;
load_previous_data = 0;
% Freq_TEXT = uicontrol('Style','text', 'Units', 'Normal', ...
% 	'String','Frequency','Position', [0.05 0.9 0.1 0.04],'FontSize',12,'HorizontalAlignment','center');
% Amp_TEXT = uicontrol('Style','text', 'Units', 'Normal',...
% 	'String','Amplitude','Position', [0.4 0.9 0.1 0.04],'FontSize',12,'HorizontalAlignment','center');
% Sample_Duration_period_TEXT = uicontrol('Style','text', 'Units', 'Normal',...
% 	'String','Sample duration period','Position', [0.7 0.9 0.1 0.04],'FontSize',12,'HorizontalAlignment','center');
% 
% Freq__BOX = uicontrol('Style','edit', 'Units', 'Normal', 'String',num2str(freq),...
%     'BackgroundColor',[1,0.9,1], 'Position', [0.15 0.898 0.1 0.045],'Callback','update','FontSize',12,'HorizontalAlignment','center');
% Amp__BOX = uicontrol('Style','edit', 'Units', 'Normal', 'String',num2str(amplitude),...
%     'BackgroundColor',[1,0.9,1], 'Position', [0.5 0.898 0.1 0.045],'Callback','update','FontSize',12,'HorizontalAlignment','center');
% Sample_Duration_period_BOX   = uicontrol('Style','edit', 'Units', 'Normal', 'String',num2str(Sample_Duration_period),...
%     'BackgroundColor',[1,0.9,1], 'Position', [0.8 0.898 0.1 0.045],'Callback','update','FontSize',12,'HorizontalAlignment','center');
figure%('CloseRequestFcn',@CB_CloseGUI)

h.Start_PUSH=uicontrol('style','push','unit','normal','pos',[.35 .01 .3 .07],...
    'string','Start','fontsize',14,'BackgroundColor',[0.9,1,1],'callback','CB_Start_motors' );
h.stop_PUSH=uicontrol('style','push','unit','normal','pos',[.7 .01 .3 .07],...
    'string','Stop motor','fontsize',14,'callback','CB_Stop_motors' );
h.start_SERIAL_PUSH=uicontrol('style','push','unit','normal','pos',[.7 .9 .2 .07],...
    'string','Start serial','fontsize',14,'callback','Start_serial' ,'BackgroundColor',[0 0.8 0.1 ]);
h.stop_SERIAL_PUSH=uicontrol('style','push','unit','normal','pos',[.7 .8 .2 .07],...
    'string','Stop serial','fontsize',14,'callback','CB_Stop_serial','BackgroundColor',[0.9 0.1 0 ]);
h.ResetGraphs_START_PUSH=uicontrol('style','push','unit','normal','pos',[.1 .9 .2 .07],...
    'string','Reset','fontsize',14,'callback','CB_Reset' );
% h.Status=uicontrol('style','frame','unit','normal','pos',[.7 .9 .02 .02],...
%     'string','','fontsize',14,'callback','CB_XXX', 'BackgroundColor',[1 0 0 ]);
% h.Label_Status=uicontrol('style','text','unit','normal','pos',[.53 .82 .15 .1],...
%     'string','SERIAL Status:','fontsize',14);
h.Analyse_PUSH=uicontrol('style','push','unit','normal','pos',[.01 .01 .3 .07],...
     'string','Analyse output','fontsize',14,'callback','Analyse_output' ); 
h.Save_Data_checkbox = uicontrol('Style','checkbox', 'Value',save_data,'string','save data','unit','normal'...
     ,'pos',[.01 .1 .04 .02],'callback','CB_save_data');
 h.Load_previous_data_checkbox  = uicontrol('Style','checkbox', 'Value',load_previous_data,'string','Load data','unit','normal'...
     ,'pos',[.06 .1 .04 .02],'callback','CB_load_previous_data');
  h.Load_previous_data_textbox  = uicontrol('Style','edit', 'string','... \insert data path here ...','unit','normal'...
     ,'pos',[.12 .1 .15 .02],'callback','CB_load_previous_data');
 h.Browse_PUSH=uicontrol('style','push','unit','normal','pos',[.27 .1 .04 .02],...
    'string','Browse','fontsize',11,'BackgroundColor',[0.9,0.7,1],'callback','CB_Browse' );

h.Sine_PLOT = axes('Position', [0.05 0.2 0.4 0.5]);
h.Furier_PLOT = axes('Position', [0.55 0.2 0.4 0.5]);
grid(h.Sine_PLOT,'on');
grid(h.Furier_PLOT,'on');
hold(h.Sine_PLOT,'on');
hold(h.Furier_PLOT,'on');